## Importing Packages

In [39]:
import numpy as np
import pandas as pd

import os

from faker import Faker

import json

## Initializing Parameters & Defining the Universe

In [40]:
BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))

In [41]:
BASE_DIR

'/Users/jaganathapandiyan/Desktop/PGDBA/Case Competitions/Zomato'

In [42]:
fake = Faker('en_IN')
np.random.seed(42)

In [43]:
# Initializing length of tables
N_CUSTOMERS = 15000
N_ORDERS = 100000

In [44]:
# Defining the universe
cities = ["Bangalore", "Mumbai", "Delhi", "Chennai"]
veg_nonveg_egg = ["veg", "nonveg", "egg"]
cuisines = ["North Indian", "South Indian", "Biryani", "Italian", "Chinese", "Fast Food", "Healthy"]
course_categories = ["mains", "appetizers", "complements", "extras", "desserts & beveragess"]


cuisine_items = {

    "North Indian Mains": [
        "Amritsari Kulcha", "Jeera Rice", "Veg Pulao", "Lachha Paratha", "Garlic Naan", "Plain Naan"
    ],
    "North Indian Appetizers":[
        "Paneer Tikka", "Tandoori Chicken", "Hara Bhara Kabab", "Chicken Seekh Kabab", "Aloo Tikki", "Fish Amritsari"
    ],
    "North Indian Complements":[
        "Butter Chicken", "Paneer Butter Masala", "Dal Makhani", "Shahi Paneer", "Kadai Paneer", "Chicken Tikka Masala", 
        "Malai Kofta", "Chicken Curry", "Mutton Rogan Josh", "Palak Paneer"
    ],
    "North Indian Extras":[
        "Boondi Raita", "Plain Curd", "Mint Chutney", "Onion Salad", "Green Salad",
        "Papad", "Masala Papad", "Pickle", "Butter", "Extra Gravy"
    ],
    "North Indian Desserts & beverages":[
        "Gulab Jamun", "Rasgulla", "Rasmalai", "Kheer", "Rabri", "Lassi", "Chai", "Badam Milk"
    ],


    "South Indian Mains": [
        "Masala Dosa", "Plain Dosa", "Rava Dosa", "Onion Dosa", "Set Dosa", "Idli", "Vada", 
        "Upma", "Pongal", "Uttapam", "Paper Dosa", "Mysore Masala Dosa", "Appam", "Curd Rice", "Lemon Rice",
        "Bisibelebath", "Neer Dosa", "Kerala Parotta", "Egg Dosa", "Mini Tiffin"
    ],
    "South Indian Appetizers":[
        "Gobi 65", "Paneer 65"
    ],
    "South Indian Complements":[
        "Sambar", "Curd", "Coconut Chutney", "Tomato Chutney", "Gunpowder"
    ],
    "South Indian Extras":[
        "Extra Sambar", "Extra Coconut Chutney", "Extra Tomato Chutney", "Extra Gunpowder",
        "Curd", "Banana Chips", "Medu Vada", "Samosa", "Masala Vada"
    ],
    "South Indian Desserts & beverages":[
        "Filter Coffee", "Buttermilk", "Kesari Bath", "Rava Kesari", "Payasam", "Mysore Pak", "Coconut Ladoo", "Jaggery Ladoo"],


    "Biryani Mains": [
        "Chicken Biryani", "Mutton Biryani", "Veg Biryani", "Paneer Biryani", "Egg Biryani", "Hyderabadi Chicken Biryani", 
        "Lucknowi Chicken Biryani", "Kolkata Chicken Biryani" ,"Donne Mutton Biryani", "Donne Chicken Biryani",
        "Boneless Chicken Biryani", "Prawn Biryani", "Fish Biryani", "Mushroom Biryani", "Paneer Tikka Biryani"
    ],
    "Biryani Appetizers":[
        "Chicken 65", "Paneer 65", "Mutton Chops", "Fish Fry", "Prawn Fry", "Chicken Tikka", "Tandoori Chicken", 
        "Paneer Tikka", "Chicken Seekh Kabab", "Hara Bhara Chicken Kabab", "Aloo Tikki", "Fish Amritsari"
    ],
    "Biryani Complements":[
        "Raita", "Green Salad", "Mint Chutney", "Onion Salad", "Cucumber Salad"
    ],
    "Biryani Extras": [
        "Extra Masala", "Extra Gravy", "Boiled Egg",
    ],
    "Biryani Desserts & beverages":[
        "Gulab Jamun", "Rasgulla", "Rasmalai", "Kheer", "Rabri", "Lassi", "Chai", "Badam Milk"
    ],


    "Italian Mains": [
        "Margherita Pizza", "Chicken Farmhouse Pizza", "Chicken Pepperoni Pizza", "Veggie Supreme Pizza", "Paneer Pizza",
        "White Sauce Pasta (Chicken)", "White Sauce Pasta (Veg)", "Red Sauce Pasta (Chicken)", "Red Sauce Pasta (Veg)",
        "Lasagna Veg", "Lasagna Chicken", "Risotto", "Garlic Bread", "Cheese Garlic Bread", "Bruschetta", "Calzone"
    ],
    "Italian Appetizers": [
        "Garlic Bread", "Cheese Garlic Bread", "Bruschetta", "Stuffed Mushrooms", "Mozzarella Sticks", "Chicken Wings",
        "Boneless Chicken Bites", "Potato Wedges"
    ],
    "Italian Complements": [
        "Marinara Sauce", "Alfredo Sauce", "Pesto Sauce", "Arrabbiata Sauce", "Bolognese Sauce", "Olives", "Jalapenos", "Mushrooms", "Bell Peppers"
    ],
    "Italian Extras": [
        "Chilli Flakes", "Oregano", "Garlic Dip", "Cheese Dip", "Sour Cream Dip", "Marinara Dip",
        "French Fries", "Onion Rings", "Coleslaw", "Caesar Salad"
    ],
    "Italian Desserts & beverages": [
        "Tiramisu", "Choco Lava Cake", "Panna Cotta", "Gelato", "Affogato", "Espresso", "Cappuccino", "Latte"
    ],


    "Chinese Mains": [
        "Veg Fried Rice", "Chicken Fried Rice", "Egg Fried Rice", "Schezwan Veg Fried Rice", 
        "Schezwan Chicken Noodles", "Veg Noodles", "Chicken Noodles", "Chicken Hakka Noodles"
    ],
    "Chinese Appetizers": [
        "Veg Spring Rolls", "Chicken Spring Rolls", "Veg Dim Sum", "Chicken Dim Sum", "Veg Manchurian", "Chicken Manchurian", 
        "Chilli Chicken", "Chilli Paneer"
    ],
    "Chinese Complements": [
        "Schezwan Sauce", "Soy Sauce", "Chilli Vinegar", "Chilli Oil", "Extra Manchurian Gravy", "Veg Clear Soup", "Chicken Clear Soup", 
    ], 
    "Chinese Extras": [
        "Extra Schezwan Sauce", "Extra Soy Sauce", "Extra Chilli Vinegar", "Extra Chilli Oil", "Extra Manchurian Gravy"
    ],
    "Chinese Desserts & beverages": [
        "Green Tea", "Black Tea", "Lemon Tea", "Chrysanthemum Tea", "Red Bean Buns", "Egg Custard Buns", "Fortune Cookies"
    ],


    "Fast Food Mains": [
        "Veg Burger", "Chicken Burger", "Cheese Burger", "Aloo Burger", "Veg Wrap", "Chicken Wrap", "Paneer Wrap", 
        "Veg Sandwich", "Chicken Sandwich", "Veg Club Sandwich"
    ],
    "Fast Food Appetizers": [
        "French Fries", "Loaded Fries", "Chicken Nuggets", "Veg Nuggets", "Potato Wedges", "Chicken Popcorn", "Veg Popcorn",
        "Chicken Wings", "Chicken Momos", "Veg Momos"
    ],
    "Fast Food Complements": [
        "Ketchup", "Mayonnaise", "Mustard", "Peri Peri Sauce", "BBQ Sauce", "Cheese Dip", "Garlic Dip", "Sour Cream Dip"
    ],
    "Fast Food Extras": [
        "Extra Cheese", "Extra Patty", "Extra Vegetables", "Onion Rings", "Coleslaw"
    ],
    "Fast Food Desserts & beverages": [
        "Chocolate Shake", "Vanilla Shake", "Strawberry Shake", "Coke", "7UP",
        "Ice Cream", "Sundae", "Mojito Mocktail", "Choco Lava Cake"
    ],


    "Healthy Mains": [
        "Veg Salad", "Chicken Salad", "Paneer Salad", "Greek Salad", "Chicken Caesar Salad", "Quinoa Salad", "Protein Bowl Veg", "Protein Bowl Chicken",
        "Brown Rice Bowl", "Grilled Chicken Bowl"
    ],
    "Healthy Appetizers": [
        "Hummus with Vegetables", "Greek Yogurt with Honey", "Fruit Salad", "Mixed Nuts", "Roasted Chickpeas", "Edamame Beans"
    ],
    "Healthy Complements": [
        "Olive Oil", "Balsamic Vinegar", "Lemon Wedges", "Chia Seeds", "Flax Seeds", "Peanut Butter"
    ],
    "Healthy Extras": [
        "Extra Avocado", "Extra Chicken", "Extra Paneer", "Boiled Egg", "Chia Seeds", "Flax Seeds", "Peanut Butter"
    ],
    "Healthy Desserts & beverages": [
        "Fruit Salad", "Greek Yogurt with Honey", "Chia Pudding", "Protein Bar", "Almond Milk Smoothie", "Green Tea", "Black Coffee",
        "Mango Smoothie", "Strawberry Smoothie", "Protein Shake Chocolate", "Protein Shake Vanilla",
    ] 
}

## Build Menu Dataframe

In [45]:
def classify_veg_type(item):

    item = item.lower()

    if any(x in item for x in ["chicken", "mutton", "fish", "prawn"]):
        return "nonveg"

    elif "egg" in item:
        return "egg"

    else:
        return "veg"

In [46]:
def extract_cuisine_and_course(category, cuisines_list):
    
    category_lower = category.lower()
    
    cuisine_match = None
    
    for cuisine in cuisines_list:
        if category_lower.startswith(cuisine.lower()):
            cuisine_match = cuisine
            break
    
    if cuisine_match is None:
        raise ValueError(f"Unknown cuisine in category: {category}")
    
    course = category_lower.replace(cuisine_match.lower(), "").strip()
    
    return cuisine_match, course

In [47]:
menu_rows = []
item_id = 0

for category, items in cuisine_items.items():

    cuisine, course = extract_cuisine_and_course(category, cuisines)

    for item in items:

        veg_type = classify_veg_type(item)

        menu_rows.append({
            "item_id": item_id,
            "item_name": item,
            "cuisine": cuisine,
            "course": course,
            "veg_type": veg_type
        })

        item_id += 1

menu_df = pd.DataFrame(menu_rows)

In [48]:
print(menu_df.head())

   item_id         item_name       cuisine course veg_type
0        0  Amritsari Kulcha  North Indian  mains      veg
1        1        Jeera Rice  North Indian  mains      veg
2        2         Veg Pulao  North Indian  mains      veg
3        3    Lachha Paratha  North Indian  mains      veg
4        4       Garlic Naan  North Indian  mains      veg

In [49]:
print("\nTotal items:", len(menu_df))

print("\nVeg distribution:")
print(menu_df["veg_type"].value_counts())

print("\nCourse distribution:")
print(menu_df["course"].value_counts())

print("\nCuisine distribution:")
print(menu_df["cuisine"].value_counts())

Total items: 295

Veg distribution:
veg_type
veg       234
nonveg     54
egg         7
Name: count, dtype: int64

Course distribution:
course
mains                   85
desserts & beverages    59
appetizers              52
complements             50
extras                  49
Name: count, dtype: int64

Cuisine distribution:
cuisine
Italian         51
South Indian    44
Biryani         43
Fast Food       42
North Indian    40
Healthy         40
Chinese         35
Name: count, dtype: int64

In [50]:
menu_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_menu.csv", index = False)

## Generate Customers Table

##### While features like $\text{cuisine\_preference}$, $\text{veg\_preference}$, $\text{app\_usage\_frequency}$, and $\text{avg\_order\_value}$ should ideally be derived variables from the $\text{Orders Table}$, it is much easier to generate the $\text{Orders Table}$ with these features. $\\[0.1in]$ Therefore, we have assumed that these feature already exist in the $\text{Customers Table}$. We can always generate these features if we have the original orders dataset.

In [51]:
customers = []

for i in range(N_CUSTOMERS):

    cuisine_probs = np.random.dirichlet(np.ones(len(cuisines)))

    customers.append({
        "customer_id": 100001 + i,
        "city": np.random.choice(cities),
        "age": int(max(18, np.random.normal(30, 15))),
        "income_bracket": np.random.choice(["low", "medium", "high"], p = [0.25, 0.6, 0.15]),
        "cuisine_preference": json.dumps(cuisine_probs.tolist()),
        "veg_nonveg_egg": json.dumps(np.random.dirichlet(np.ones(len(veg_nonveg_egg))).tolist()),
        "app_usage_frequency": np.random.choice(["low", "medium", "high"], p = [0.4, 0.5, 0.1]),
        "avg_per_item_value": int(min(max(250, np.random.normal(250, 100)), 800)),
        "avg_items": int(min(max(1, np.random.normal(6, 2)), 12))
    })

customers_df = pd.DataFrame(customers)

In [52]:
customers_df["avg_order_value"] = customers_df["avg_per_item_value"] * customers_df["avg_items"]

In [53]:
print(customers_df.shape)
customers_df.head()

(15000, 10)

,customer_id,city,age,income_bracket,cuisine_preference,veg_nonveg_egg,app_usage_frequency,avg_per_item_value,avg_items,avg_order_value
0,100001,Chennai,18,medium,"[0.07682670448608449, 0.49280510347876866, 0.2...","[0.014066964943178606, 0.310126194044882, 0.67...",low,250,6,1500
1,100002,Chennai,23,medium,"[0.08504241993465063, 0.007959640521941116, 0....","[0.040657793322410186, 0.7995268851439777, 0.1...",low,250,7,1750
2,100003,Chennai,38,medium,"[0.02021291476784117, 0.22670813031561424, 0.1...","[0.2112418094975387, 0.759929915147514, 0.0288...",medium,250,1,250
3,100004,Bangalore,18,medium,"[0.23755760741745766, 0.11813899733150535, 0.0...","[0.6959167146249469, 0.1740137005224957, 0.130...",medium,282,5,1410
4,100005,Delhi,37,high,"[0.008574915733587391, 0.47969697157591096, 0....","[0.19444531612670904, 0.45515609059606027, 0.3...",medium,380,5,1900

In [54]:
customers_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_customers.csv", index = False)

## Generate Orders Table

#### Initialzing the Parameters

In [55]:
P_MAIN = 0.85

P_APPETIZER_IF_MAIN = 0.25
P_COMPLEMENT_IF_MAIN = 0.80
P_EXTRA_IF_MAIN = 0.60
P_DESSERT_IF_MAIN = 0.25

P_APPETIZER_IF_NO_MAIN = 0.65
P_COMPLEMENT_IF_NO_MAIN = 0.10
P_EXTRA_IF_NO_MAIN = 0
P_DESSERT_IF_NO_MAIN = 0.10

In [56]:
# Item selection Logic

prob_table_if_main = {
    "mains": 0.05,  # allow for multiple mains in some cases
    "appetizers": P_APPETIZER_IF_MAIN,
    "complements": P_COMPLEMENT_IF_MAIN,
    "extras": P_EXTRA_IF_MAIN,
    "desserts & beverages": P_DESSERT_IF_MAIN
}

prob_table_if_no_main = {
    "mains": P_MAIN,
    "appetizers": P_APPETIZER_IF_NO_MAIN,
    "complements": P_COMPLEMENT_IF_NO_MAIN,
    "extras": P_EXTRA_IF_NO_MAIN,
    "desserts & beverages": P_DESSERT_IF_NO_MAIN
}

In [57]:
usage_weights = {"high": 0.6,
                 "medium": 0.3,
                 "low": 0.2}

### Defining function for orders and recommendations

In [58]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [59]:
def ordered_items(cuisine, items_number):

    cuisine_menu = menu_df[menu_df["cuisine"] == cuisine]

    selected_items = []
    selected_item_ids = set()

    main_selected = False

    while len(selected_items) < items_number:
        # choose correct probability table
        if main_selected:
            prob_table = prob_table_if_main
        else:
            prob_table = prob_table_if_no_main

        categories = list(prob_table.keys())
        probs = np.array(list(prob_table.values()))

        # normalize
        probs = probs / probs.sum()

        chosen_course = np.random.choice(categories, p = probs)
        # sample item from category
        recommendation_choice = cuisine_menu[
            (cuisine_menu["course"] == chosen_course) &
            (~cuisine_menu["item_id"].isin(selected_item_ids))
        ]

        if len(recommendation_choice) == 0:
            continue

        item = recommendation_choice.sample(1)["item_id"].iloc[0]

        selected_items.append(item)
        selected_item_ids.add(item)

        if chosen_course == "main":
            main_selected = True

    return selected_items

In [60]:
def recommended_items(cuisine, items_ordered, n_recommend = 3):

    cuisine_menu = menu_df[menu_df["cuisine"] == cuisine]

    # Removing already ordered items
    candidate_menu = cuisine_menu[~cuisine_menu["item_id"].isin(items_ordered)]

    # Identify what courses are already ordered
    ordered_courses = cuisine_menu[cuisine_menu["item_id"].isin(items_ordered)]["course"].unique().tolist()
    has_main = "main" in ordered_courses

    if has_main:
        rec_probs = prob_table_if_main
    else:
        rec_probs = prob_table_if_no_main

    recommended_ids = []
    recommended_names = []


    while len(recommended_ids) < n_recommend:
        categories = list(rec_probs.keys())
        probs = np.array(list(rec_probs.values()))
        probs = probs / probs.sum()

        chosen_category = np.random.choice(categories, p=probs)

        subset = candidate_menu[
            (candidate_menu["course"] == chosen_category) &
            (~candidate_menu["item_id"].isin(recommended_ids))
        ]

        if len(subset) == 0:
            continue

        item_id = subset.sample(1)["item_id"].iloc[0]
        item_name = subset[subset["item_id"] == item_id]["item_name"].iloc[0]

        recommended_ids.append(item_id)
        recommended_names.append(item_name)

    return recommended_ids, recommended_names

In [61]:
item_course_map = dict(zip(menu_df["item_id"], menu_df["course"]))
item_cuisine_map = dict(zip(menu_df["item_id"], menu_df["cuisine"]))

# Optional but recommended
item_popularity = {item: np.random.uniform(0.2, 1.0)
                   for item in menu_df["item_id"]}

In [62]:
complement_rules = {
    "main": ["complement", "extras", "dessert"],
    "appetizer": ["main", "dessert"],
    "complement": ["main", "extras"],
    "extras": ["main", "complement"],
    "dessert": ["main", "appetizer"]
}

In [63]:
def recommendation_click_probability(
    cust,
    ordered_ids,
    rec_id,
    position
):

    ordered_courses = {
        item_course_map[i] for i in ordered_ids
    }

    rec_course = item_course_map[rec_id]
    rec_cuisine = item_cuisine_map[rec_id]

    # Complement score
    complement_score = max(
        [rec_course in complement_rules.get(course, [])
        for course in ordered_courses],
        default = False
    )

    complement_score = 0.6 if complement_score else 0.15

    # Cuisine match score
    cuisine_match = 0.6 if rec_cuisine in cuisines else 0.3

    # User engagement
    usage_score = {
        "low": 0.2,
        "medium": 0.4,
        "high": 0.7
    }[cust.app_usage_frequency]

    # Position bias
    position_score = 1/ (position + 1)

    # Popularity
    popularity_score = item_popularity.get(rec_id, 0.5) * 0.6

    # Basket size influence
    basket_score = min(len(ordered_ids)/ 8, 0.6)

    intercept = -2.2

    # Final score
    score = (
        intercept +
        1.0 * complement_score +
        0.7 * cuisine_match +
        0.9 * usage_score +
        0.8 * position_score +
        0.6 * popularity_score +
        0.5 * basket_score +
        np.random.normal(0, 0.4)
    )

    return sigmoid(score)

In [64]:
def simulate_recommendation_click(cust, ordered_ids, recommendation_ids):

    clicked = []

    for pos, rec_id in enumerate(recommendation_ids, start = 1):

        prob = recommendation_click_probability(cust, ordered_ids, rec_id, pos)

        if np.random.rand() < prob:
            if np.random.rand() < 0.55:
                clicked.append(1)
            else:
                clicked.append(0)
        else:
            clicked.append(0)

    return clicked

### Using the defined functions to simulate a logical $\text{Orders Table}$

In [65]:
orders = []

for i in range(N_ORDERS):

    # A random customer is chosen to place an order, with higher probability for more frequent app users
    cust = customers_df.sample(1,
                               weights = customers_df["app_usage_frequency"].map(usage_weights)
                               ).iloc[0]
    
    order_time = fake.date_time_between(start_date = "-1y", end_date = "now").strftime("%H:%M:%S")

    # Extract cuisine probability vector
    probs = np.array(json.loads(cust["cuisine_preference"]))
    cuisine = np.random.choice(cuisines, p = probs)

    # Choose cuisine using those probabilities
    cuisine = np.random.choice(cuisines, p = probs)
    items_number = int(min(max(1, np.random.normal(cust["avg_items"], 3)), 12))
    items_ordered_ids = ordered_items(cuisine, items_number)

    recommendation_ids, recommended_names = recommended_items(cuisine, items_ordered_ids, n_recommend = 3)

    recommendation_added = False

    if recommendation_ids:
        match = int(cuisine == cust.cuisine_preference.split(',')[0].strip())
        score = (
            1.5 * match +
            0.5 * (cust.app_usage_frequency == "high") +
            np.random.normal(0,1)
        )


    recommendation_added = simulate_recommendation_click(cust, items_ordered_ids, recommendation_ids)
    
    orders.append({
        "order_id": 8000000 + i,
        "customer_id": cust.customer_id,
        "order_time": order_time,
        "cuisine": cuisine,
        "items_ordered_id": items_ordered_ids,
        "items_ordered_name": menu_df[menu_df["item_id"].isin(items_ordered_ids)]["item_name"].tolist(),
        "recommendation_shown_id": recommendation_ids,
        "recommendation_shown_name": recommended_names,
        "recommendation_added_1": recommendation_added[0],
        "recommendation_added_2": recommendation_added[1],
        "recommendation_added_3": recommendation_added[2],
    })

orders_df = pd.DataFrame(orders)

In [66]:
print(orders_df.shape)
orders_df.head()

(100000, 11)

,order_id,customer_id,order_time,cuisine,items_ordered_id,items_ordered_name,recommendation_shown_id,recommendation_shown_name,recommendation_added_1,recommendation_added_2,recommendation_added_3
0,8000000,111723,06:40:25,South Indian,"[60, 53, 61, 54, 79, 52]","[Appam, Curd Rice, Lemon Rice, Gobi 65, Paneer...","[49, 42, 62]","[Uttapam, Rava Dosa, Sambar]",0,0,1
1,8000001,102102,22:07:05,Chinese,[188],[Veg Dim Sum],"[189, 184, 190]","[Chicken Dim Sum, Chicken Noodles, Veg Manchur...",0,1,0
2,8000002,102664,16:38:39,Biryani,"[84, 96, 90, 109, 88, 102, 104, 99]","[Chicken Biryani, Egg Biryani, Lucknowi Chicke...","[106, 98, 120]","[Paneer Tikka, Paneer Tikka Biryani, Rasgulla]",0,0,0
3,8000003,100561,15:16:51,Healthy,[270],[Edamame Beans],"[260, 265, 267]","[Quinoa Salad, Hummus with Vegetables, Fruit S...",0,0,0
4,8000004,106394,06:24:26,North Indian,"[1, 7, 6]","[Jeera Rice, Paneer Tikka, Tandoori Chicken]","[3, 2, 12]","[Lachha Paratha, Veg Pulao, Butter Chicken]",0,1,0

In [68]:
orders_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_orders.csv", index = False)

## Sanity Checking the Click Through Rate

In [69]:
print('CTR of recommendation 1:', round(orders_df['recommendation_added_1'].sum()/len(orders_df) * 100, 2),'%')
print('CTR of recommendation 2:', round(orders_df['recommendation_added_2'].sum()/len(orders_df) * 100, 2),'%')
print('CTR of recommendation 3:', round(orders_df['recommendation_added_3'].sum()/len(orders_df) * 100, 2),'%')

CTR of recommendation 1: 21.96 %
CTR of recommendation 2: 20.55 %
CTR of recommendation 3: 19.54 %