## Importing Packages

In [40]:
import numpy as np
import pandas as pd

import os

from faker import Faker

import json

## Initializing Parameters & Defining the Universe

In [41]:
BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))

In [42]:
fake = Faker('en_IN')
np.random.seed(42)

In [43]:
# Initializing length of tables
N_CUSTOMERS = 15000
N_ORDERS = 100000

In [44]:
# Defining the universe
cities = ["Bangalore", "Mumbai", "Delhi", "Chennai"]
veg_types = ["veg", "nonveg", "egg"]
cuisines = ["North Indian", "South Indian", "Biryani", "Italian", "Chinese", "Fast Food", "Healthy"]
course_categories = ["mains", "appetizers", "complements", "extras", "desserts & beveragess"]


cuisine_items = {

    "North Indian Mains": [
        "Amritsari Kulcha", "Jeera Rice", "Veg Pulao", "Lachha Paratha", "Garlic Naan", "Plain Naan", 'Aloo Paratha', 
        "Gobhi Paratha", "Paneer Paratha", "Tandoori Roti", "Rumali Roti", "Chole Bhature", "Rajma Chawal"
    ],
    "North Indian Appetizers":[
        "Paneer Tikka", "Tandoori Chicken", "Hara Bhara Chicken Kabab", "Chicken Seekh Kabab", "Aloo Tikki", "Fish Amritsari"
        "Egg Bhurji", "Paneer Pakora", "Vegetable Pakora", "Chicken Pakora", "Egg Pakora"
    ],
    "North Indian Complements":[
        "Butter Chicken", "Paneer Butter Masala", "Dal Makhani", "Shahi Paneer", "Kadai Paneer", "Chicken Tikka Masala", 
        "Malai Kofta", "Chicken Curry", "Mutton Rogan Josh", "Palak Paneer", "Egg Curry", "Egg Masala", "Egg Bhurji Masala"
    ],
    "North Indian Extras":[
        "Boondi Raita", "Plain Curd", "Mint Chutney", "Onion Salad", "Green Salad",
        "Papad", "Masala Papad", "Pickle", "Butter", "Extra Gravy", "Boiled Egg"
    ],
    "North Indian Desserts & beverages":[
        "Gulab Jamun", "Rasgulla", "Rasmalai", "Kheer", "Rabri", "Lassi", "Chai", "Badam Milk"
    ],


    "South Indian Mains": [
        "Masala Dosa", "Plain Dosa", "Rava Dosa", "Onion Dosa", "Set Dosa", "Idli", "Vada", 
        "Upma", "Pongal", "Uttapam", "Paper Dosa", "Mysore Masala Dosa", "Appam", "Curd Rice", "Lemon Rice",
        "Bisibelebath", "Neer Dosa", "Kerala Parotta", "Egg Dosa", "Mini Tiffin", "Egg Uttapam", "Egg Parotta",
        "Chicken Dosa", "Chicken Uttapam", "Chicken Parotta"
    ],
    "South Indian Appetizers":[
        "Gobi 65", "Paneer 65", "Chicken 65", "Medu Vada", "Egg 65", "Egg Kalaki"
    ],
    "South Indian Complements":[
        "Sambar", "Curd", "Coconut Chutney", "Tomato Chutney", "Mint Chutney", "Spicy Onion Chutney", "Mushroom Curry", 
        "Chicken Curry", "Mutton Curry", "Egg Curry", "Chettinadu Chicken Curry", "Chettinadu Mutton Curry", 
        "Chettinadu Egg Curry"
    ],
    "South Indian Extras":[
        "Extra Sambar", "Extra Coconut Chutney", "Extra Tomato Chutney", "Gunpowder",
        "Medu Vada", "Samosa", "Masala Vada"
    ],
    "South Indian Desserts & beverages":[
        "Filter Coffee", "Buttermilk", "Rava Kesari", "Payasam", "Mysore Pak", "Coconut Ladoo", "Jaggery Ladoo"],


    "Biryani Mains": [
        "Chicken Biryani", "Mutton Biryani", "Veg Biryani", "Paneer Biryani", "Egg Biryani", "Egg 65 Biryani", 
        "Hyderabadi Chicken Biryani", "Lucknowi Chicken Biryani", "Kolkata Chicken Biryani" ,"Donne Mutton Biryani", 
        "Donne Chicken Biryani", "Boneless Chicken Biryani", "Prawn Biryani", "Fish Biryani", "Mushroom Biryani"
    ],
    "Biryani Appetizers":[
        "Chicken 65", "Paneer 65", "Mutton Chops", "Fish Fry", "Prawn Fry", "Chicken Tikka", "Tandoori Chicken", 
        "Paneer Tikka", "Chicken Seekh Kabab", "Hara Bhara Chicken Kabab", "Aloo Tikki", "Fish Amritsari", "Egg Bhurji",
        "Egg 65", "Egg Pakora", "Chicken Pakora"
    ],
    "Biryani Complements":[
        "Chettinad Chicken Curry", "Chettinad Mutton Curry", "Chettinad Egg Curry", "Chicken Curry", "Mutton Curry", "Egg Curry",
        "Paneer Butter Masala", "Dal Makhani", "Shahi Paneer", "Kadai Paneer", "Chicken Tikka Masala", "Malai Kofta",
        "Palak Paneer", "Egg Masala", "Egg Bhurji Masala"
    ],
    "Biryani Extras": [
        "Extra Masala", "Extra Gravy", "Boiled Egg", "Raita", "Green Salad", "Mint Chutney", "Onion Salad", 
        "Cucumber Salad", "Salan", "Mirchi Ka Salan"
    ],
    "Biryani Desserts & beverages":[
        "Gulab Jamun", "Rasgulla", "Rasmalai", "Kheer", "Rabri", "Lassi", "Chai", "Badam Milk"
    ],


    "Italian Mains": [
        "Margherita Pizza", "Chicken Farmhouse Pizza", "Chicken Pepperoni Pizza", "Veggie Supreme Pizza", "Paneer Pizza",
        "White Sauce Pasta (Chicken)", "White Sauce Pasta (Veg)", "Red Sauce Pasta (Chicken)", "Red Sauce Pasta (Veg)",
        "Lasagna Veg", "Lasagna Chicken", "Chicken Risotto", "Garlic Bread", "Cheese Garlic Bread"
    ],
    "Italian Appetizers": [
        "Garlic Bread", "Cheese Garlic Bread", "Bruschetta", "Stuffed Mushrooms", "Mozzarella Sticks", "Chicken Wings",
        "Boneless Chicken Bites", "Potato Wedges", "Poached Eggs", "Sunny Side Up Eggs", "CHicken Caesar Salad", "Veg Caesar Salad"
    ],
    "Italian Complements": [
        "Marinara Sauce", "Alfredo Sauce", "Pesto Sauce", "Arrabbiata Sauce", "Bolognese Sauce"
    ],
    "Italian Extras": [
        "Chilli Flakes", "Oregano", "Garlic Dip", "Cheese Dip", "Sour Cream Dip", "Marinara Dip",
        "French Fries", "Onion Rings", "Coleslaw"
    ],
    "Italian Desserts & beverages": [
        "Tiramisu", "Choco Lava Cake", "Panna Cotta", "Gelato", "Affogato", "Espresso", "Cappuccino", "Latte"
    ],


    "Chinese Mains": [
        "Veg Fried Rice", "Chicken Fried Rice", "Egg Fried Rice", "Schezwan Veg Fried Rice", 
        "Schezwan Chicken Fried Rice", "Schezwan Egg Fried Rice", "Veg Noodles", "Chicken Noodles", 
        "Egg Noodles", "Veg Hakka Noodles",  "Chicken Hakka Noodles", "Egg Hakka Noodles"
    ],
    "Chinese Appetizers": [
        "Veg Spring Rolls", "Chicken Spring Rolls", "Veg Dim Sum", "Chicken Dim Sum", "Veg Manchurian (Dry)", "Chicken Manchurian (Dry)", 
        "Chilli Chicken (Dry)", "Chilli Paneer (Dry)", "Egg Manchurian (Dry)", "Egg Chilli (Dry)", "Chicken Lollipop"
    ],
    "Chinese Complements": [
        "Chilli Chicken (Gravy)", "Chilli Paneer (Gravy)", "Egg Manchurian (Gravy)", "Egg Chilli (Gravy)", "Chicken Manchurian (Gravy)",
        "Veg Manchurian (Gravy)", "Schezwan Chicken (Gravy)", "Schezwan Paneer (Gravy)", "Schezwan Egg (Gravy)"
    ], 
    "Chinese Extras": [
        "Extra Schezwan Sauce", "Extra Soy Sauce", "Extra Chilli Vinegar", "Extra Chilli Oil", "Extra Manchurian Gravy"
    ],
    "Chinese Desserts & beverages": [
        "Green Tea", "Black Tea", "Lemon Tea", "Egg Custard Buns", "Vanilla Ice Cream", "Chocolate Ice Cream", 
        "Vanilla Milkshake", "Chocolate Milkshake"
    ],


    "Fast Food Mains": [
        "Veg Burger", "Chicken Burger", "Aloo Burger", "Veg Wrap", "Chicken Wrap", "Egg Wrap", "Paneer Wrap", 
        "Veg Sandwich", "Chicken Sandwich", "Egg Sandwich"
    ],
    "Fast Food Appetizers": [
        "Chicken Nuggets", "Veg Nuggets", "Potato Wedges", "Chicken Popcorn", "Veg Popcorn",
        "Chicken Wings", "Chicken Momos", "Veg Momos"
    ],
    "Fast Food Complements": [
        "French Fries", "Loaded Fries", "Cheese Fries", "Onion Rings", "Baked Beans"
    ],
    "Fast Food Extras": [
        "Extra Cheese", "Ketchup", "Mayonnaise", "Mustard", "Peri Peri Sauce", "BBQ Sauce", 
        "Cheese Dip", "Garlic Dip", "Sour Cream Dip"
    ],
    "Fast Food Desserts & beverages": [
        "Chocolate Milkshake", "Vanilla Milkshake", "Strawberry Milkshake", "Coke", "7UP",
        "Vanilla Ice Cream", "Chocolate Ice Cream", "Brownie Sundae", "Mojito", "Choco Lava Cake"
    ],


    "Healthy Mains": [
        "Veg Salad", "Chicken Salad", "Paneer Salad", "Egg Salad", "Greek Salad", "Chicken Caesar Salad", "Quinoa Salad", 
        "Protein Bowl Veg", "Protein Bowl Chicken", "Brown Rice Veg Bowl", "Grilled Chicken Bowl", "Egg Rice Bowl"
    ],
    "Healthy Appetizers": [
        "Fruit Salad", "Mixed Nuts", "Roasted Chickpeas", "Edamame Beans", "Egg White Omelette", "Grilled Chicken Strips", 
        "Egg Sandwich"
    ],
    "Healthy Complements": [
        "Lemon Wedges", "Chia Seeds", "Flax Seeds", "Peanut Butter", "Boiled Egg", "Avocado Slices", "Tofu Cubes"
    ],
    "Healthy Extras": [
        "Extra Avocado", "Extra Chicken", "Extra Paneer", "Extra Egg"
    ],
    "Healthy Desserts & beverages": [
        "Chia Pudding", "Protein Bar", "Almond Milk Smoothie", "Green Tea", "Black Coffee",
        "Mango Smoothie", "Strawberry Smoothie", "Protein Shake Chocolate", "Protein Shake Vanilla",
    ] 
}

## Build Menu Dataframe

In [45]:
def classify_veg_type(item):

    item = item.lower()

    if any(x in item for x in ["chicken", "mutton", "fish", "prawn"]):
        return "nonveg"

    elif "egg" in item:
        return "egg"

    else:
        return "veg"

In [46]:
def extract_cuisine_and_course(category, cuisines_list):
    
    category_lower = category.lower()
    
    cuisine_match = None
    
    for cuisine in cuisines_list:
        if category_lower.startswith(cuisine.lower()):
            cuisine_match = cuisine
            break
    
    if cuisine_match is None:
        raise ValueError(f"Unknown cuisine in category: {category}")
    
    course = category_lower.replace(cuisine_match.lower(), "").strip()
    
    return cuisine_match, course

In [47]:
menu_rows = []
item_id = 0

for category, items in cuisine_items.items():

    cuisine, course = extract_cuisine_and_course(category, cuisines)

    for item in items:

        veg_type = classify_veg_type(item)

        menu_rows.append({
            "item_id": item_id,
            "item_name": item,
            "cuisine": cuisine,
            "course": course,
            "veg_type": veg_type
        })

        item_id += 1

menu_df = pd.DataFrame(menu_rows)

In [48]:
print(menu_df.head())

   item_id         item_name       cuisine course veg_type
0        0  Amritsari Kulcha  North Indian  mains      veg
1        1        Jeera Rice  North Indian  mains      veg
2        2         Veg Pulao  North Indian  mains      veg
3        3    Lachha Paratha  North Indian  mains      veg
4        4       Garlic Naan  North Indian  mains      veg

In [49]:
print("\nTotal items:", len(menu_df))

print("\nVeg distribution:")
print(menu_df["veg_type"].value_counts())

print("\nCourse distribution:")
print(menu_df["course"].value_counts())

print("\nCuisine distribution:")
print(menu_df["cuisine"].value_counts())

Total items: 351

Veg distribution:
veg_type
veg       232
nonveg     76
egg        43
Name: count, dtype: int64

Course distribution:
course
mains                   101
appetizers               70
complements              67
desserts & beverages     58
extras                   55
Name: count, dtype: int64

Cuisine distribution:
cuisine
Biryani         64
South Indian    58
North Indian    55
Italian         48
Chinese         45
Fast Food       42
Healthy         39
Name: count, dtype: int64

In [50]:
item_veg_type_map = dict(zip(menu_df["item_id"], menu_df["veg_type"]))

In [51]:
menu_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_menu.csv", index = False)

## Generate Customers Table

##### While features like $\text{cuisine\_preference}$, $\text{veg\_preference}$, $\text{app\_usage\_frequency}$, and $\text{avg\_order\_value}$ should ideally be derived variables from the $\text{Orders Table}$, it is much easier to generate the $\text{Orders Table}$ with these features. $\\[0.1in]$ Therefore, we have assumed that these feature already exist in the $\text{Customers Table}$. We can always generate these features if we have the original orders dataset.

In [52]:
def generate_veg_pref():
    r = np.random.rand()
    
    # 20% pure veg
    if r < 0.20:
        return [1.0, 0.0, 0.0]

    # 15% veg + egg only
    elif r < 0.35:
        veg_egg = np.random.dirichlet([3, 1])  # bias toward veg
        return [veg_egg[0], 0.0, veg_egg[1]]

    # remaining 65% mixed
    else:
        mixed = np.random.dirichlet([2, 3, 1])  # slight nonveg bias
        return mixed.tolist()

In [53]:
customers = []

for i in range(N_CUSTOMERS):

    cuisine_probs = np.random.dirichlet(np.ones(len(cuisines)))

    customers.append({
        "customer_id": 100001 + i,
        "city": np.random.choice(cities),
        "age": int(max(18, np.random.normal(30, 15))),
        "income_bracket": np.random.choice(["low", "medium", "high"], p = [0.25, 0.6, 0.15]),
        "cuisine_preference": json.dumps(cuisine_probs.tolist()),
        "veg_nonveg_egg": json.dumps(generate_veg_pref()),
        "app_usage_frequency": np.random.choice(["low", "medium", "high"], p = [0.4, 0.5, 0.1]),
        "avg_per_item_value": int(min(max(250, np.random.normal(250, 100)), 800)),
        "avg_items": int(min(max(1, np.random.normal(6, 2)), 12))
    })

customers_df = pd.DataFrame(customers)

In [54]:
customers_df["avg_order_value"] = customers_df["avg_per_item_value"] * customers_df["avg_items"]

In [55]:
print(customers_df.shape)
customers_df.head()

(15000, 10)

,customer_id,city,age,income_bracket,cuisine_preference,veg_nonveg_egg,app_usage_frequency,avg_per_item_value,avg_items,avg_order_value
0,100001,Chennai,18,medium,"[0.07682670448608449, 0.49280510347876866, 0.2...","[1.0, 0.0, 0.0]",medium,250,6,1500
1,100002,Chennai,23,medium,"[0.08504241993465063, 0.007959640521941116, 0....","[1.0, 0.0, 0.0]",medium,250,7,1750
2,100003,Chennai,38,medium,"[0.02021291476784117, 0.22670813031561424, 0.1...","[0.9813473327590709, 0.0, 0.018652667240929177]",medium,250,3,750
3,100004,Bangalore,41,medium,"[0.23755760741745766, 0.11813899733150535, 0.0...","[0.9252756837300214, 0.0, 0.07472431626997857]",medium,250,7,1750
4,100005,Bangalore,18,medium,"[0.0008896555622665301, 0.27150296811136226, 0...","[0.536913920215734, 0.29325287761987556, 0.169...",high,313,6,1878

### Rounding to 2 decimal places

In [56]:
def round_and_fix_probs(prob_list, decimals = 2):

    probs = np.array(prob_list)
    rounded = np.round(probs, decimals)
    diff = 1.0 - rounded.sum()

    # Add correction to largest element
    idx = np.argmax(rounded)
    rounded[idx] += diff

    rounded = np.clip(rounded, 0, 1)

    return rounded.tolist()

In [57]:
customers_df["veg_nonveg_egg"] = customers_df["veg_nonveg_egg"].apply(lambda x: json.dumps(round_and_fix_probs(json.loads(x), 2)))
customers_df["cuisine_preference"] = customers_df["cuisine_preference"].apply(lambda x: json.dumps(round_and_fix_probs(json.loads(x), 2)))

In [58]:
print(customers_df.shape)
customers_df.head()

(15000, 10)

,customer_id,city,age,income_bracket,cuisine_preference,veg_nonveg_egg,app_usage_frequency,avg_per_item_value,avg_items,avg_order_value
0,100001,Chennai,18,medium,"[0.08, 0.48, 0.22, 0.15, 0.03, 0.03, 0.01]","[1.0, 0.0, 0.0]",medium,250,6,1500
1,100002,Chennai,23,medium,"[0.09, 0.01, 0.6, 0.04, 0.02, 0.16, 0.08]","[1.0, 0.0, 0.0]",medium,250,7,1750
2,100003,Chennai,38,medium,"[0.02, 0.23, 0.11, 0.03, 0.13, 0.01, 0.47]","[0.98, 0.0, 0.02]",medium,250,3,750
3,100004,Bangalore,41,medium,"[0.24, 0.12, 0.04, 0.08, 0.07, 0.2799999999999...","[0.93, 0.0, 0.07]",medium,250,7,1750
4,100005,Bangalore,18,medium,"[0.0, 0.27, 0.2, 0.21, 0.24, 0.01, 0.07]","[0.54, 0.29, 0.17]",high,313,6,1878

In [175]:
customers_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_customers.csv", index = False)

## Generate Orders Table

### Initialzing the Parameters

In [ ]:
P_MAIN = 0.85

P_APPETIZER_IF_MAIN = 0.40
P_COMPLEMENT_IF_MAIN = 0.80
P_EXTRA_IF_MAIN = 0.60
P_DESSERT_IF_MAIN = 0.20

P_APPETIZER_IF_NO_MAIN = 0.75
P_COMPLEMENT_IF_NO_MAIN = 0.10
P_EXTRA_IF_NO_MAIN = 0.00
P_DESSERT_IF_NO_MAIN = 0.20

In [177]:
# Item selection Logic

prob_table_if_main = {
    "mains": 0.05,  # allow for multiple mains in some cases
    "appetizers": P_APPETIZER_IF_MAIN,
    "complements": P_COMPLEMENT_IF_MAIN,
    "extras": P_EXTRA_IF_MAIN,
    "desserts & beverages": P_DESSERT_IF_MAIN
}

prob_table_if_no_main = {
    "mains": P_MAIN,
    "appetizers": P_APPETIZER_IF_NO_MAIN,
    "complements": P_COMPLEMENT_IF_NO_MAIN,
    "extras": P_EXTRA_IF_NO_MAIN,
    "desserts & beverages": P_DESSERT_IF_NO_MAIN
}

In [178]:
usage_weights = {"high": 0.6,
                 "medium": 0.3,
                 "low": 0.2}

### Defining function for orders and recommendations

In [179]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [180]:
def ordered_items(cuisine, items_number, veg_probs):

    cuisine_menu = menu_df[menu_df["cuisine"] == cuisine]

    selected_items = []
    selected_item_ids = set()

    main_selected = False

    while len(selected_items) < items_number:
        # choose correct probability table
        if main_selected:
            cat_prob_table = prob_table_if_main
        else:
            cat_prob_table = prob_table_if_no_main

        categories = list(cat_prob_table.keys())
        cat_probs = np.array(list(cat_prob_table.values()))

        # normalize
        cat_probs = cat_probs / cat_probs.sum()

        chosen_course = np.random.choice(categories, p = cat_probs)
        chosen_veg_type = np.random.choice(veg_types, p = veg_probs)
        # sample item from category
        recommendation_choice = cuisine_menu[
            (cuisine_menu["course"] == chosen_course) &
            (cuisine_menu["veg_type"] == chosen_veg_type) &
            (~cuisine_menu["item_id"].isin(selected_item_ids))
        ]

        if len(recommendation_choice) == 0:
            continue

        item = recommendation_choice.sample(1)["item_id"].iloc[0]

        selected_items.append(item)
        selected_item_ids.add(item)

        if chosen_course == "main":
            main_selected = True

    return selected_items

In [181]:
def recommended_items(cuisine, items_ordered, n_recommend = 3):

    cuisine_menu = menu_df[menu_df["cuisine"] == cuisine]

    # Removing already ordered items
    candidate_menu = cuisine_menu[~cuisine_menu["item_id"].isin(items_ordered)]

    # Identify what courses are already ordered
    ordered_courses = cuisine_menu[cuisine_menu["item_id"].isin(items_ordered)]["course"].unique().tolist()
    has_main = "main" in ordered_courses

    if has_main:
        rec_probs = prob_table_if_main
    else:
        rec_probs = prob_table_if_no_main

    recommended_ids = []
    recommended_names = []


    while len(recommended_ids) < n_recommend:
        categories = list(rec_probs.keys())
        probs = np.array(list(rec_probs.values()))
        probs = probs / probs.sum()

        chosen_category = np.random.choice(categories, p = probs)

        subset = candidate_menu[
            (candidate_menu["course"] == chosen_category) &
            (~candidate_menu["item_id"].isin(recommended_ids))
        ]

        if len(subset) == 0:
            continue

        item_id = subset.sample(1)["item_id"].iloc[0]
        item_name = subset[subset["item_id"] == item_id]["item_name"].iloc[0]

        recommended_ids.append(item_id)
        recommended_names.append(item_name)

    return recommended_ids, recommended_names

In [182]:
item_course_map = dict(zip(menu_df["item_id"], menu_df["course"]))
item_cuisine_map = dict(zip(menu_df["item_id"], menu_df["cuisine"]))

# Optional but recommended
item_popularity = {item: np.random.uniform(0.2, 1.0)
                   for item in menu_df["item_id"]}

In [ ]:
complement_rules = {
    "mains": ["appetizers", "complements", "extras", "desserts & beverages"],
    "appetizers": ["mains", "desserts & beverages"],
    "complements": ["mains"],
    "extras": ["mains", "appetizers"],
    "desserts & beverages": ["mains", "appetizers"]
}

In [184]:
def recommendation_click_probability(cust, ordered_ids, rec_id, position):

    ordered_courses = {
        item_course_map[i] for i in ordered_ids
    }

    rec_course = item_course_map[rec_id]
    rec_cuisine = item_cuisine_map[rec_id]

    # Complement score
    complement_score = max(
        [rec_course in complement_rules.get(course, [])
        for course in ordered_courses],
        default = False
    )

    complement_score = 0.6 if complement_score else 0.15

    # Cuisine match score
    cuisine_match = 0.6 if rec_cuisine in cuisines else 0.3

    # User engagement
    usage_score = {
        "low": 0.2,
        "medium": 0.4,
        "high": 0.7
    }[cust.app_usage_frequency]

    # Position bias
    position_score = 1/ (position + 1)

    # Popularity
    popularity_score = item_popularity.get(rec_id, 0.5) * 0.6

    # Basket size influence
    basket_score = min(len(ordered_ids)/ 8, 0.6)

    intercept = -2.2

    # Final score
    score = (
        intercept +
        1.0 * complement_score +
        0.7 * cuisine_match +
        0.9 * usage_score +
        0.8 * position_score +
        0.6 * popularity_score +
        0.5 * basket_score +
        np.random.normal(0, 0.4)
    )

    return sigmoid(score)

In [185]:
def simulate_recommendation_click(cust, ordered_ids, recommendation_ids):

    clicked = []

    # Check if order is strictly veg
    ordered_veg_types = [item_veg_type_map[i] for i in ordered_ids]

    all_veg_order = all(v == "veg" for v in ordered_veg_types)

    for pos, rec_id in enumerate(recommendation_ids, start=1):

        rec_veg_type = item_veg_type_map[rec_id]

        # On veg days, customer won't click on non veg recommendation
        if all_veg_order and (rec_veg_type == "nonveg" or rec_veg_type == "egg"):
            clicked.append(0)
            continue

        prob = recommendation_click_probability(cust, ordered_ids, rec_id, pos)

        if np.random.rand() < prob:
            if np.random.rand() < 0.55:
                clicked.append(1)
            else:
                clicked.append(0)
        else:
            clicked.append(0)

    return clicked

### Using the defined functions to simulate a logical $\text{Orders Table}$

In [186]:
orders = []

for i in range(N_ORDERS):

    # A random customer is chosen to place an order, with higher probability for more frequent app users
    cust = customers_df.sample(1,
                               weights = customers_df["app_usage_frequency"].map(usage_weights)
                               ).iloc[0]
    
    order_time = fake.date_time_between(start_date = "-1y", end_date = "now").strftime("%H:%M:%S")

    # Extract cuisine probability vector
    cat_probs = np.array(json.loads(cust["cuisine_preference"]))
    cuisine = np.random.choice(cuisines, p = cat_probs)

    # Choose cuisine using those probabilities
    cuisine = np.random.choice(cuisines, p = cat_probs)

    # Choose veg type using veg/nonveg/egg probabilities
    veg_probs = np.array(json.loads(cust["veg_nonveg_egg"]))
    veg_type = np.random.choice(veg_types, p = veg_probs)

    items_number = int(min(max(1, np.random.normal(cust["avg_items"], 3)), 12))
    items_ordered_ids = ordered_items(cuisine, items_number, veg_probs)

    recommendation_ids, recommended_names = recommended_items(cuisine, items_ordered_ids, n_recommend = 3)

    recommendation_added = False

    if recommendation_ids:
        match = int(cuisine == cust.cuisine_preference.split(',')[0].strip())
        score = (
            1.5 * match +
            0.5 * (cust.app_usage_frequency == "high") +
            np.random.normal(0,1)
        )


    recommendation_added = simulate_recommendation_click(cust, items_ordered_ids, recommendation_ids)
    
    orders.append({
        "order_id": 8000000 + i,
        "customer_id": cust.customer_id,
        "order_time": order_time,
        "cuisine": cuisine,
        "items_ordered_id": items_ordered_ids,
        "items_ordered_name": menu_df[menu_df["item_id"].isin(items_ordered_ids)]["item_name"].tolist(),
        "recommendation_shown_id": recommendation_ids,
        "recommendation_shown_name": recommended_names,
        "recommendation_added_1": recommendation_added[0],
        "recommendation_added_2": recommendation_added[1],
        "recommendation_added_3": recommendation_added[2],
    })

orders_df = pd.DataFrame(orders)

In [187]:
print(orders_df.shape)
orders_df.head()

(100000, 11)

,order_id,customer_id,order_time,cuisine,items_ordered_id,items_ordered_name,recommendation_shown_id,recommendation_shown_name,recommendation_added_1,recommendation_added_2,recommendation_added_3
0,8000000,111723,15:28:06,South Indian,"[55, 61, 58, 60, 50, 66, 48, 83, 53, 65]","[Pongal, Paper Dosa, Curd Rice, Bisibelebath, ...","[43, 40, 56]","[Onion Dosa, Masala Dosa, Neer Dosa]",0,0,0
1,8000001,100407,17:35:10,Biryani,"[88, 92, 90, 104, 94, 107, 110, 101, 99, 103, ...","[Egg Biryani, Lucknowi Chicken Biryani, Kolkat...","[111, 87, 109]","[Raita, Paneer Biryani, Aloo Tikki]",0,0,0
2,8000002,102995,00:43:21,Italian,"[128, 140, 149, 130, 137, 142]","[Chicken Farmhouse Pizza, Veggie Supreme Pizza...","[139, 141, 144]","[Garlic Bread, Bruschetta, Cheese Garlic Bread]",0,0,0
3,8000003,113031,03:53:11,Healthy,"[263, 261, 255, 269, 260, 264, 258, 257]","[Veg Salad, Paneer Salad, Greek Salad, Quinoa ...","[262, 266, 256]","[Protein Bowl Chicken, Greek Yogurt with Honey...",0,0,0
4,8000004,100038,13:18:16,Fast Food,"[219, 232]","[Paneer Wrap, Veg Momos]","[213, 221, 218]","[Veg Burger, Chicken Sandwich, Chicken Wrap]",0,0,0

In [188]:
orders_df.to_csv(BASE_DIR + "/Data Generation/Data/zomato_orders.csv", index = False)

## Sanity Checking the Click Through Rate

In [189]:
print('CTR of recommendation 1:', round(orders_df['recommendation_added_1'].sum()/len(orders_df) * 100, 2),'%')
print('CTR of recommendation 2:', round(orders_df['recommendation_added_2'].sum()/len(orders_df) * 100, 2),'%')
print('CTR of recommendation 3:', round(orders_df['recommendation_added_3'].sum()/len(orders_df) * 100, 2),'%')

CTR of recommendation 1: 20.69 %
CTR of recommendation 2: 18.99 %
CTR of recommendation 3: 18.31 %